name: VMAgent-dev
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.10.0
  - astor=0.8.1
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - cffi=1.14.0
  - gast=0.4.0
  - google-pasta=0.2.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - importlib-metadata=2.0.0
  - intel-openmp=2020.1
  - krb5=1.17.1
  - ld_impl_linux-64=2.35.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgfortran4=7.5.0
  - liblapack=3.8.0
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libprotobuf=3.12.1
  - libssh2=1.9.0
  - markdown=3.2.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - ncurses=6.1
  - ninja=1.10.0
  - numpy=1.16.5
  - numpy-base=1.18.1
  - openssl=1.1.1k
  - pip=20.1.1
  - protobuf=3.12.1
  - pycparser=2.20
  - python=3.7.3
  - python_abi=3.7
  - readline=8.0
  - setuptools=46.4.0
  - six=1.15.0
  - sqlite=3.30.1
  - termcolor=1.1.0
  - tk=8.6.10
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.3.0
  - zlib=1.2.11
  - pip:
    - atari-py==0.2.6
    - backcall==0.2.0
    - cloudpickle==1.3.0
    - decorator==5.0.9
    - future==0.18.2
    - grpcio==1.32.0
    - gym==0.10.9
    - idna==2.9
    - ipdb==0.13.9
    - ipython==7.24.1
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - joblib==1.0.1
    - kiwisolver==1.2.0
    - matplotlib==3.2.1
    - matplotlib-inline==0.1.2
    - numpy-stl==2.11.2
    - opencv-python==4.5.1.48
    - pandas==1.2.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.18
    - ptyprocess==0.7.0
    - pyglet==1.5.0
    - pygments==2.9.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - python-utils==2.4.0
    - pytz==2021.1
    - pyyaml==5.4.1
    - requests==2.23.0
    - scipy==1.4.1
    - toml==0.10.2
    - traitlets==5.0.5
    - urllib3==1.25.9
    - wcwidth==0.2.5
    - dash==1.21.0
    - dash-daq==0.5.0
    - dash_bootstrap_components==0.13.0
    - dash_bootstrap_templates==0.1.1
    - gunicorn>=19.9.0
    - plotly~=5.3.0