# --- Default ---

# Environment Options
num_process: 5

# Learning Options
learn_interval: 1
train_n: 100
max_epoch: 100
batch_size: 1024

lr: 0.005
gamma: 0.95
tau: 0.1
target_update_interval: 1

memory: 'replay'
capacity: 1000000
test_interval: 5
