N: 100
cpu: 40
mem: 90
allow_release: True
growing_nums: 2
expand_threshold: 0.7
double_thr: 32
env: deployenv_alibaba
node_num: -1
pod_num: -1
batch_size: 64
train_n: 1
tau: 0.5
max_epoch: 1000
capacity: 10000